source 'https://rubygems.org'

gem 'activesupport', '4.1.8'
gem 'cucumber', '3.0.1'
gem 'nokogiri', '1.6.8'
gem 'rake', '11.3.0'
gem 'require_all'
gem 'rspec', '3.7.0'
gem 'selenium-webdriver', '3.6.0'
gem 'simplecov'
gem 'simplecov-rcov'
gem 'slowhandcuke', '0.0.3'
gem 'watir-launcher', '1.0.6'
gem 'watir', '6.8.0'
gem 'debase', '0.2.1'
gem 'working_hours', '1.1.2'
gem 'tzinfo-data', '1.2016.7'
gem 'business_time', '0.7.6'
gem 'watir-scroll', '0.3.0'
